### ISSUE TITLE
swc minifier breaks escaped unicode

### ISSUE THREAD

**Issue by stormslowly** [swc-project/swc#11098]
### Describe the bug

```js
JSON.parse('{"bug": " \\"\\\\uD83D\\\\uDC49\\""}')
```
after swc minified, throw runtime error as 

```
Uncaught SyntaxError: Unexpected token '�', "{"bug": " \"\�\�\""}" is not valid JSON
```

### Input code

```typescript
JSON.parse('{"bug": " \\"\\\\uD83D\\\\uDC49\\""}')
```

### Config

```json

```

### Link to the code that reproduces this issue

https://play.swc.rs/?version=1.13.5&code=H4sIAAAAAAAAA%2FMK9vfTK0gsKk7VUK9WSipNV7JSUFKIiVGKAYJSFwtjFwjD2cQSKKhUq64JACfeS8kyAAAA&config=H4sIAAAAAAAAA11Puw7CUAjd%2BxUNs6uLm3Fx8SNuKjW3ua8ANW2a%2FruQvtQNzhOmqq6h4wYu9aSjLjgIUnLhjqEgsRJCPZ4WsjhipF2siPDwI1GIxyTOUJCxIDfki8DCzlsOoea88RrCLceISf6KxNELxTKQz6sZok%2B%2BHb%2FbmxwtysytC4xLSbUWQczPPuDxm91jmWqLOXUMu9LzY9NuVxx1hlTzB3dfn5orAQAA

### Expected behavior

minfied code should executable·

### Actual behavior

```txt
Uncaught SyntaxError: Unexpected token '�', "{"bug": " \"\�\�\""}" is not valid JSON
```

### Version

1.13.5

**Comment by kdy1** [comment]
@CPunisher I think this is already fixed on the main branch. The problem is that I'm still fixing the publish pipeline

**Comment by CPunisher** [comment]
> [@CPunisher](https://github.com/CPunisher) I think this is already fixed on the main branch. The problem is that I'm still fixing the publish pipeline

I check on the main branch. But it isn't fixed. Is there the pr?

**Comment by kdy1** [comment]
Sorry. I was talking about the [`dev/rust`](https://github.com/swc-project/swc/tree/dev/rust) branch which has https://github.com/swc-project/swc/pull/11066 merged

**Comment by CPunisher** [comment]
> Sorry. I was talking about the [`dev/rust`](https://github.com/swc-project/swc/tree/dev/rust) branch which has [#11066](https://github.com/swc-project/swc/pull/11066) merged

This is actually another small bug that can be fixed without breaking change. I will submit the pr later.

**Comment by CPunisher** [comment]
Fixed in https://github.com/swc-project/swc/pull/11144
