### ISSUE TITLE
Dynamic import

### ISSUE THREAD

**Issue by Gargron** [swc-project/swc#140]
I'd love to try this library out for Mastodon, to see if it helps with compile time, but currently I'm stuck on dynamic `import()` calls throwing an error.

**Comment by kdy1** [comment]
@Gargron I implemented parsing and code generation of dynamic imports. I were not sure how to process it, but webpack seems to handle it.

Fixed with swc@1.0.3

**Comment by Gargron** [comment]
Amazing, thank you!

**Comment by Gargron** [comment]
I'm sorry, I have upgraded to 1.0.3, and modified .swcrc like this:

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true,
      "dynamicImport": true
    }
  }
}
```

Unfortunately, I still get:

```
error: 'import', and 'export' cannot be used outside of module code
  --> /home/[REDACTED]/mastodon/app/javascript/packs/public.js:84:7
   |
84 |       import(/* webpackChunkName: "containers/media_container" */ '../mastodon/containers/media_container')
   |       ^^^^^^

fatal runtime error: failed to initiate panic, error 5
```

If it matters, the JS file in question is: https://github.com/tootsuite/mastodon/blob/master/app/javascript/packs/public.js#L84

**Comment by Gargron** [comment]
However, I understand Mastodon is a really large application, and our babel.config.js is not just a few lines, so I do not want to waste your time... This is probably not the last place the migration would get stuck...

**Comment by kdy1** [comment]
I would love to see swc being used, so I don't consider helping you waste of time. If you want to use swc, I'll help you as you need.

Fixed (really) with swc@1.0.4

**Comment by Gargron** [comment]
Side note: Your OpenCollective page is missing a "contribute" button for me...

**Comment by kdy1** [comment]
@Gargron Thank you for information. Fixed it.

**Comment by fzaninotto** [comment]
I have the same problem with the latest version, swc 1.0.15.

**Comment by kdy1** [comment]
@fabiosantoscode What is your `.swcrc?`

**Comment by fzaninotto** [comment]
```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": false
    }
  }
}
```

**Comment by kdy1** [comment]
You should add 

```json
{
  "jsc": {
    "parser": {
      "dynamicImport": true
    }
  }
}
```
