### ISSUE TITLE
Imported function is not bundled using spack

### ISSUE THREAD

**Issue by tmpfs** [swc-project/swc#2124]
**Describe the bug**

An imported function is not being included in the bundle leading to a runtime `ReferenceError`.

**Input code**

MVP: https://github.com/tmpfs/spack-tree-shaking

**Config**

https://github.com/tmpfs/spack-tree-shaking/blob/main/spack.config.js

**Expected behavior**

I expect the code for the `memoize` function to be included in the generated bundle.

The bundle output in `dist/main.js` looks like this but `memoize` is imported from `lodash` in [util.js](https://github.com/tmpfs/spack-tree-shaking/blob/main/src/util.js):

```javascript
const getEnvironmentTypeMemo = memoize((url)=>{
});
const getEnvironmentType = (url = window.location.href)=>getEnvironmentTypeMemo(url)
;
const name = getEnvironmentType();
console.log(name);
```

**Version**
The version of @swc/core: 1.2.76

**Additional context**

Possibly an issue with the tree shaking algorithm.

**Comment by tmpfs** [comment]
It appears that the issue is to do with loading CJS via an ESM `import` and indirection across a module boundary.

If we import the mock `lodash.js` file directly in `index.js` then the code is included in the bundle (see https://github.com/tmpfs/spack-tree-shaking/blob/main/src/index.js#L3-L5) but when we add a level of indirection via `util.js` then the code for `lodash.js` is **not** included in the bundle.

**Comment by tmpfs** [comment]
Note also that commenting out these lines: https://github.com/tmpfs/spack-tree-shaking/blob/main/src/lodash.js#L16-L17 and using indirection of `exports` like this: https://github.com/tmpfs/spack-tree-shaking/blob/main/src/lodash.js#L20-L21 will also cause the code to be included even with the extra indirection via `util.js`.

**Comment by kumavis** [comment]
spooky 👻

**Comment by tmpfs** [comment]
Hi @kdy1, we have reduced this as far as we think possible, it would be great if you could take a look and confirm the issue we are seeing, thanks :+1:  

This is blocking our journey trying to get `spack` bundling our code so very much looking forward to moving past this issue, anything I can do to help please let me know :pray:

**Comment by kdy1** [comment]
Thanks for reducing!
I'll take a look.

Btw, do you use spack from js? I'm asking this to know if I should publish a new version after fixing this.

**Comment by tmpfs** [comment]
> Thanks for reducing!
> I'll take a look.
> 
> Btw, do you use spack from js? I'm asking this to know if I should publish a new version after fixing this.

I was calling `spack` via `@swc/cli` which I believe goes through the node bindings, so I think the answer is yes but I am not totally sure about how the JS API is exposed, I haven't tried to use it yet!

**Comment by kdy1** [comment]
If you use cli, it mean you are using it via node bindings.
Anyway, I fixed it.

**Comment by tmpfs** [comment]
> If you use cli, it mean you are using it via node bindings.
> Anyway, I fixed it.

Thanks! That's awesome :grin:

**Comment by tmpfs** [comment]
@kdy1, this is not completely fixed it seems.

I managed to reproduce this bug again in our project and came back to the MVP and noticed that a different style of re-export causes the same problem. It works with a direct re-export (in `util.js`):

```javascript
export {memoize} from './lodash';
```

But an `import` followed by `export`:

```javascript
import { memoize } from './lodash';
export {
  memoize,
}
```

Causes the dependency not to be included in the bundle, `dist/main.js` now looks like this:

```javascript
const name = memoize();
console.log(name);
```

I have updated https://github.com/tmpfs/spack-tree-shaking/ to reproduce the issue again.

Thanks for all your help :pray:

**Comment by tmpfs** [comment]
Hi @kdy1, anything I can to to help move this along? Really keen to see what the next error is :+1:

**Comment by kdy1** [comment]
@tmpfs I'm not sure, because the issue isn't fixed yet because I have lots of tasks to do.
