### ISSUE TITLE
export * as Foo from 'bar' not supported

### ISSUE THREAD

**Issue by natemara** [swc-project/swc#226]
I tried this: 

```
export * as Foo from 'bar';
```

I expected to see this happen: 

```
module.exports = {
  Foo: require('bar'),
};
```

Instead, this happened: 

```
error: Expected Word(from), got Some(Word(as))
 --> test.js:1:10
  |
1 | export * as Foo from 'bar';
  |          ^^
```

I'm using CLI 0.1.12, @swc/core 1.0.15

**Comment by kdy1** [comment]
Fixed with`@swc/core@1.0.16`

**Comment by natemara** [comment]
Still having this issue after updating to 1.0.18, and adding the `exportNamespaceFrom` line to my `.swcrc`,

```
error: Expected Comma, got Some(Str { value: Atom('bar' type=inline), has_escape: false })
 --> test.js:1:22
  |
1 | export * as Foo from 'bar';
  |                      ^^^^^
```

**Comment by kdy1** [comment]
@natemara I can't reproduce this.
See https://github.com/swc-project/node-swc/blob/4b098fdb524b565e86e973e32c46f62abfd8d117/__tests__/api_test.js#L12-L25

Did you specified `exportNamespaceFrom` in `jsc.parser`?

**Comment by natemara** [comment]
here is my `.swcrc` 

```
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "dynamicImport": true,
      "classProperty": true,
      "exportDefaultFrom": true,
      "exportNamespaceFrom": true,
      "jsx": true
    }
  },
  "module": {
    "type": "commonjs"
  }
}
```

And the entirety of the file I'm trying to compile:

```
export * as Foo from 'bar';
```

**Comment by kdy1** [comment]
It errors only when `exportDefaultFrom: true` is specified.

**Comment by natemara** [comment]
Yes, I just realized that too

**Comment by kdy1** [comment]
Fixed with `@swc/core` `1.0.20`
