### ISSUE TITLE
wasm-unknonw-unknown plugin panic with unknown import

### ISSUE THREAD

**Issue by RiESAEX** [swc-project/swc#3591]
### Describe the bug

```
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke `../unknown/unknown.wasm` as js transform plugin at ../unknown/unknown.wasm

Caused by:
    0: Failed to create plugin instance
    1: Error while importing "env"."now": unknown import. Expected Function(FunctionType { params: [], results: [F64] })', crates/swc/src/plugin.rs:135:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failed to handle: failed to invoke plugin: failed to invoke `../unknown/unknown.wasm` as js transform plugin at ../unknown/unknown.wasm

Caused by:
    0: Failed to create plugin instance
    1: Error while importing "env"."now": unknown import. Expected Function(FunctionType { params: [], results: [F64] })
```

### Input code

```typescript
code from scaffolding
```

### Expected behavior

no panic

### Version

@swc/core 1.2.141 
swc_plugin v0.27.1 
rustc 1.57.0 (f1edd0429 2021-11-29)

**Comment by kwonoj** [comment]
🤔 huh, thought this is cleared.

@RiESAEX if specify this manually https://github.com/swc-project/swc/pull/3538/files#diff-abd28eda086bb8ab6301ca0a2c063752c324d21d2e579361135664cc63c30f6bL152 does it work?

**Comment by RiESAEX** [comment]
@kwonoj it work.
I think https://github.com/Amanieu/parking_lot/issues/269 is fixed in parking_lot 0.12.0
https://github.com/Amanieu/parking_lot/blob/master/CHANGELOG.md#parking_lot-0120-parking_lot_core-090-lock_api-046-2022-01-28

**Comment by kwonoj** [comment]
I thought I bumped up to latest 🤔 let me quickly retry.

**Comment by dsherret** [comment]
It's not fixed yet when I try. We need string_cache to update: https://github.com/servo/string-cache/pull/254

**Comment by kwonoj** [comment]
:oh-no: reopening for now.

**Comment by RiESAEX** [comment]
looks like we don't need browserslist-rs to update?
just tried with swc_plugin0.39.0 and @swc/core 1.2.161 @swc/cli 0.1.56, and it works.

**Comment by kwonoj** [comment]
🤔 when I tried patches it seems to require bumping browserslist as well. If it's working it's good, but let's close this along with browserslist bump to be sure.

**Comment by kwonoj** [comment]
I believe we're good to go: https://github.com/swc-project/swc/pull/4435
