### ISSUE TITLE
ReferenceError after minification referencing function defined later

### ISSUE THREAD

**Issue by evantd** [swc-project/swc#3748]
### Describe the bug

The result of minifying & webpack-bundling `tabbable@4.0.0` (a transitive dependency in my project) results in a `ReferenceError`.

I'm using:
```
    "@swc/core": "^1.2.145",
    "@swc/helpers": "^0.3.5",
    "@swc/jest": "^0.2.18",
    "swc-loader": "^0.1.15",
```
with `webpack@5.69.0` via:
```javascript
// ...
                      new TerserPlugin({
                          parallel: true,
                          minify: TerserPlugin.swcMinify,
                          terserOptions: {
                              compress: {
                                  drop_console: true, // eslint-disable-line camelcase
                              },
                          },
                      }),
// ...
            rules: [
                {
                    test: /\.m?js$/,
                    type: 'javascript/auto',
                    resolve: {
                        fullySpecified: false,
                    },
                },
                {
                    test: /\.[jt]sx?$/,
                    exclude: excludeNodeModules,
                    use: [
                        {
                            loader: 'swc-loader',
                            options: { env: { targets: 'node 12' } },
                        },
                    ],
                },
// ...
```

### Input code

```typescript
function tabbable(el, options) { /* ... */ }
tabbable.isTabbable = isTabbable;
tabbable.isFocusable = isFocusable;
// ...
function isTabbable(node) { /* ... */ }
// ...
function isFocusable(node) { /* ... */ }
```

### Config

```json
{
    "sourceMaps": true,
    "module": { "type": "es6", "strict": true, "noInterop": false },
    "env": { "coreJs": 2 },
    "jsc": {
        "externalHelpers": true,
        "parser": {
            "syntax": "typescript",
            "tsx": true,
            "decorators": false,
            "dynamicImport": true
        },
        "keepClassNames": false,
        "baseUrl": "."
    }
}
```

### Playground link

https://play.swc.rs/?version=1.2.145&code=H4sIAAAAAAAAA61X3W%2FbNhB%2Fz1%2FB5KGSUVfNXuMaRZe1WB6WFWv2ZAQoLZ4srjKpkVQco83%2FvuOXREkO1g4DAkfkffDudx88PlBFSioYZ9TAJ2igNFJpsiabM0IyLtrOZEv7qR3Nfxt4NFQB9Su6qRVU936x7YyRwn9vDN1yweAx0GjHuNyUUhglGx02HziD2aZbA%2F4xjjoauL8S0uTT3fVFRRsNF%2FcLlLpfnT2c8gVdmftX%2FCW5yLNltlidObE9NWUN1m9zbEFW5H0DezyKrNdrknXoRMUFsAyNe0uqTpSGS0HyBfn6hFtXkb1olTTSqiiixm%2FfThH1b57cW3mS7QDbL9xMWNHi3gCEYWuRyKFZEtnaPY02oUlhgQ7FLzzh6xMKE2IdVrDrGqruggIXcYTQE6VioIBNiYHaw2n3oSn%2B7kAdo3Xvmiaf4b1wsrwieTCm4KJsOgbXGFCKwCpvtOcJyBUlRV3Wsbm%2ByE7GxrxTih4T%2FHTDSyho2zbHwSi9WM1ki07omlcGjwtUG9an6DFPbEg%2B70J6W4kKY5hztOFyRTh5k%2BpuQOxMjdsvX0a7e2qanXrDPcgehnOubyUDF30udtH3GJTBIUTDFgYXHQTxmYV4zA5MXCWiq%2F64EzKY%2BpcD0tOMKdpO1zNVT5gRGnqhaSZ5oUglhMmys0n%2Fu%2BW7QqB7Cqb2jTXjau7NwCQQoIQhEp5OBTHWigXV1cXENCdRaKlMbn9%2Bn5AXnr6nbR7LL6eIDuJiOiUILawxeLTnw4iU1ORT0HwlBJGRRasztDTuFFxHEbR0WKxSjg%2BIne5Z%2BlXaH%2F4lhazFPsA2A5zhz2Rdr93LOFZsKJZZRHV%2FUGzvY3qadP6wN%2BQSiTGrAhCuja%2FOfMAiOMqm89PImWcMP%2FdLUyt5IAIO5L1SUuXZrXQJQrAh2FuGZS4tZi3G8pxqMq4AnGmLmaFh%2FT34Tp34DnjHIbFbBeOOzgbkf%2BWMgbixN%2FQ0KJ7U7%2F4I2rZSqmjN9fddpiHXM14puodskd6uiePPOfm%2FhO95m%2F97HCcGjwM5T%2B2vQ6Nx2%2B%2BMsYC1VGm4ET5IBYrZfY5zEuRZZM0WS%2FLTZe%2BfLUJ6m6eKFouka%2FS7VuD1a%2FIzIqcBxzZmITOR83PsoZ%2FxglAKfWqO7qIKc9T7MEc5mHXQpaU1wdRwRG0iM6SmD0Bofyyh0XyiWyh5xW0UjkSDWRKqNbZzwk2myWURvOH6enyex6t36DIJhMMomj0G%2FFRTzumSbD3yfRuO0i7s22H5Fmmj64a8QvJ45yqVf5VIT4v4pEepHc6RKc5umLSllk31JWU802Lo7hbrykvf3H78824mPusFqZKx9hcvglYckLzK2gnPdCbt%2FEe0KSs2U3b6mhjrTQmo93zo9wllVoTXNZRfgA0sYQB2A5kb3oahzJFPzWM2TR0RR7Ci9BrTyacPhp%2FRhtni9P00dbHvcoXAQC7GTddV3V3NNTm4eqNlKTt8eVgHsAwJsB1g18Wh6lBj8pOj7HxNOqTJTsmuRVluaseu8QSvk2PNAHYfO2aisr0m9sUQWLAt7aCIjwGr6RPga8dHUx5wJP8lVMZ8vvfPwo2N%2BfrCyV7cb6xn64uMvCS9o%2FidXdz7tu0eDh5YP4yO4hYNWCSt4Dyy45XWS669hafzP0Ec3ZdVhT3pI75TEcwtYF8nomsaRAp%2FsGXhZcPAoFOWYvHVAWAqcIb1rz8MChcPXHNbvRgPLjTeRJZj2A68S38q1aSRqBD%2Fu%2BAFRUyietuaO4xjKzW3hl%2BRij8CK8gHH%2Br90v5yRZxq3nBzxEijIon29xgwHjo5Ug7QNMWkXYz8doBZr%2F0wdi33GDlgn8wxNq0iOWzWDvaSdThrwmOLzde9jvtB9B9FIug7ORAAAA%3D%3D&config=H4sIAAAAAAAAA3VUTY%2FUMAz9KyhHNOyyHBCaExISYg9w44RWUSZ1OlnSJIqdbqvV%2FnecfndmOLV5%2Fnj2s5NXgSEnDT9VRHGklOEgmlBlB%2BL4KqiP%2FBWAn8VBICWraXby4dETpBDF0SiH8HYQ4NshSKUaiLOxTwXvHj4Jtj2jLjboOMYr9wNchLQwRpUQUnHA3pPqOLZQo042ElMTdrNrBTokRaEED8QM9V41Vj82MaSpPmZsrLemLzl1aGICxPLPteUGPK3RKqXwslRyCsGB8ldnqVBabriGDbEOzrFuIFu19lLYVLIY%2FA7KBJWMrNc23FeWbGA9Ns2AqqRm4VbEJtBkW9g4cR528hgc7MEKTrmui5YjNbTKZUWwnLtBCiZd4s7BIkmTPV5AU7Vj4AiNjU5e1sgElJOffZ6D9Tst%2FgJwnU4h8oQ29Q%2B44VnsPc0NL%2BsND5L6BXVhU5WHmpuT1pqlw1I1JLKwOCWosobSoV6TT%2BCuIbQVSDCG5V6C8cWSPm%2BqKosZzGJn2ZRZhzAe5bxUe7TswRX4ncui7TwmvFF0vsSwb07BXaVogM6huoJZCQqXYOIV7uIlmn0FrDNUG0PGcpxvk%2FL19CaE6KAFtx%2FTf4d8A4vJtmVq%2B9tg4cs6CMXLYR8%2Bzm%2FL2xj5rZD82iWMrNJwsb%2FevxfHP%2BKOP08HISWeFY%2F4g7EdbyiglLOdAOn%2Btv2JeU4K4Xfi7sSd2Lwigwz%2FAChR53otBQAA

### Expected behavior

`tabbable.isFocusable` should get minified to an anonymous function (as it does in the playground and as `tabbable.isTabbable` does in my setup) rather than elided.

Since it works in the playground, I'm guessing this is due to some interaction with `swc-loader` and/or `webpack`.

### Actual behavior

`tabbable.isFocusable` is elided from the output, though a dangling reference to it remains.

```javascript
function a(g, j) { /* ... */ }
// ...
(a.isTabbable = function (a) { /* ... */ }),
    (a.isFocusable = isFocusable),
    b.concat('iframe').join(','),
    (c.exports = a);
```

`isTabbable` is mangled to an anonymous function, but `isFocusable` is missing, and it's right-hand-side is not mangled, so it results in a `ReferenceError`.

### Version

1.2.145

### Additional context

I also tried dropping the `TerserPlugin` and just configuring minification with `swc-loader`, but that didn't seem to minify anything at all.

**Comment by evantd** [comment]
> I also tried dropping the TerserPlugin and just configuring minification with swc-loader, but that didn't seem to minify anything at all.

I just realized that this is because minification is a totally separate API from transformation rather than an option on the transform API.

**Comment by evantd** [comment]
I just had the brilliant idea to throw my unminified bundle content into the playground in order to reproduce it, since it seems to be something to do with webpack's output, but... it worked fine. I really wish I could figure out a decent repro case for this (that doesn't leak a bunch of IP).

**Comment by evantd** [comment]
I just tried upgrading to @swc/core@1.2.146, @swc/helpers@0.3.6, @swc/jest@0.2.20, and swc-loader@0.1.15 in case this turned out to be a duplicate of something that was fixed in 1.2.146, but no luck. I imagine the next thing I should try is flipping configuration switches to see which minification features contribute to it.

**Comment by evantd** [comment]
`defaults:false` works around this, and it doesn't seem to interact with anything else, since turning everything else off, but leaving `defaults` on still produces the `ReferenceError`.

**Comment by kdy1** [comment]
Thank you so much for the investigation!
As you might already know, reducing input and finding cause are almost all of the bugfix, especially for the minifier :)

**Comment by kdy1** [comment]
Oh... Seems like it's already fixed in v1.2.146?

I tested and v1.2.143 also worked

**Comment by evantd** [comment]
I definitely still see the problem in `1.2.146`. I can keep trying to put a shareable repro case together.

**Comment by kdy1** [comment]
Can you create a repro?
I need an input file to debug it.

**Comment by evantd** [comment]
Yep, I'll keep working on it. It's bulky & proprietary right now, so I just need to trim it down to make it more portable. It's also not what I'm *supposed* to be working on, so it's not getting my full attention.

**Comment by evantd** [comment]
Stepping through `webpack` (really `terser-webpack-plugin`) in the debugger, I see it call `swc.minify(code, swcOptions)`, and it gives results that have a `ReferenceError`. The playground does not produce the same problem.

### Input
#### swcOptions
```javascript
{
  compress: {},
  module: false,
  ecma: 2015,
  mangle: true,
  sourceMap: undefined,
}
```
#### code
```javascript
/******/ (() => { // webpackBootstrap
/******/ 	var __webpack_modules__ = ({

/***/ 190:
/***/ ((module) => {

var candidateSelectors = [
    'input',
    'select',
    'textarea',
    'a[href]',
    'button',
    '[tabindex]',
    'audio[controls]',
    'video[controls]',
    '[contenteditable]:not([contenteditable="false"])', 
];
var candidateSelector = candidateSelectors.join(',');
var matches = typeof Element === 'undefined' ? function() {} : Element.prototype.matches || Element.prototype.msMatchesSelector || Element.prototype.webkitMatchesSelector;
function tabbable(el, options) {
    options = options || {};
    var regularTabbables = [];
    var orderedTabbables = [];
    var candidates = el.querySelectorAll(candidateSelector);
    if (options.includeContainer) {
        if (matches.call(el, candidateSelector)) {
            candidates = Array.prototype.slice.apply(candidates);
            candidates.unshift(el);
        }
    }
    var i, candidate, candidateTabindex;
    for(i = 0; i < candidates.length; i++){
        candidate = candidates[i];
        if (!isNodeMatchingSelectorTabbable(candidate)) continue;
        candidateTabindex = getTabindex(candidate);
        if (candidateTabindex === 0) {
            regularTabbables.push(candidate);
        } else {
            orderedTabbables.push({
                documentOrder: i,
                tabIndex: candidateTabindex,
                node: candidate
            });
        }
    }
    var tabbableNodes = orderedTabbables.sort(sortOrderedTabbables).map(function(a) {
        return a.node;
    }).concat(regularTabbables);
    return tabbableNodes;
}
tabbable.isTabbable = isTabbable;
tabbable.isFocusable = isFocusable;
function isNodeMatchingSelectorTabbable(node) {
    if (!isNodeMatchingSelectorFocusable(node) || isNonTabbableRadio(node) || getTabindex(node) < 0) {
        return false;
    }
    return true;
}
function isTabbable(node) {
    if (!node) throw new Error('No node provided');
    if (matches.call(node, candidateSelector) === false) return false;
    return isNodeMatchingSelectorTabbable(node);
}
function isNodeMatchingSelectorFocusable(node) {
    if (node.disabled || isHiddenInput(node) || isHidden(node)) {
        return false;
    }
    return true;
}
var focusableCandidateSelector = candidateSelectors.concat('iframe').join(',');
function isFocusable(node) {
    if (!node) throw new Error('No node provided');
    if (matches.call(node, focusableCandidateSelector) === false) return false;
    return isNodeMatchingSelectorFocusable(node);
}
function getTabindex(node) {
    var tabindexAttr = parseInt(node.getAttribute('tabindex'), 10);
    if (!isNaN(tabindexAttr)) return tabindexAttr;
    // Browsers do not return `tabIndex` correctly for contentEditable nodes;
    // so if they don't have a tabindex attribute specifically set, assume it's 0.
    if (isContentEditable(node)) return 0;
    return node.tabIndex;
}
function sortOrderedTabbables(a, b) {
    return a.tabIndex === b.tabIndex ? a.documentOrder - b.documentOrder : a.tabIndex - b.tabIndex;
}
function isContentEditable(node) {
    return node.contentEditable === 'true';
}
function isInput(node) {
    return node.tagName === 'INPUT';
}
function isHiddenInput(node) {
    return isInput(node) && node.type === 'hidden';
}
function isRadio(node) {
    return isInput(node) && node.type === 'radio';
}
function isNonTabbableRadio(node) {
    return isRadio(node) && !isTabbableRadio(node);
}
function getCheckedRadio(nodes) {
    for(var i = 0; i < nodes.length; i++){
        if (nodes[i].checked) {
            return nodes[i];
        }
    }
}
function isTabbableRadio(node) {
    if (!node.name) return true;
    // This won't account for the edge case where you have radio groups with the same
    // in separate forms on the same page.
    var radioSet = node.ownerDocument.querySelectorAll('input[type="radio"][name="' + node.name + '"]');
    var checked = getCheckedRadio(radioSet);
    return !checked || checked === node;
}
function isHidden(node) {
    // offsetParent being null will allow detecting cases where an element is invisible or inside an invisible element,
    // as long as the element does not use position: fixed. For them, their visibility has to be checked directly as well.
    return node.offsetParent === null || getComputedStyle(node).visibility === 'hidden';
}
module.exports = tabbable;


/***/ })

/******/ 	});
/************************************************************************/
/******/ 	// The module cache
/******/ 	var __webpack_module_cache__ = {};
/******/ 	
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/ 		// Check if module is in cache
/******/ 		var cachedModule = __webpack_module_cache__[moduleId];
/******/ 		if (cachedModule !== undefined) {
/******/ 			return cachedModule.exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = __webpack_module_cache__[moduleId] = {
/******/ 			// no module.id needed
/******/ 			// no module.loaded needed
/******/ 			exports: {}
/******/ 		};
/******/ 	
/******/ 		// Execute the module function
/******/ 		__webpack_modules__[moduleId](module, module.exports, __webpack_require__);
/******/ 	
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/ 	
/************************************************************************/
/******/ 	/* webpack/runtime/compat get default export */
/******/ 	(() => {
/******/ 		// getDefaultExport function for compatibility with non-harmony modules
/******/ 		__webpack_require__.n = (module) => {
/******/ 			var getter = module && module.__esModule ?
/******/ 				() => (module['default']) :
/******/ 				() => (module);
/******/ 			__webpack_require__.d(getter, { a: getter });
/******/ 			return getter;
/******/ 		};
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/define property getters */
/******/ 	(() => {
/******/ 		// define getter functions for harmony exports
/******/ 		__webpack_require__.d = (exports, definition) => {
/******/ 			for(var key in definition) {
/******/ 				if(__webpack_require__.o(definition, key) && !__webpack_require__.o(exports, key)) {
/******/ 					Object.defineProperty(exports, key, { enumerable: true, get: definition[key] });
/******/ 				}
/******/ 			}
/******/ 		};
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/hasOwnProperty shorthand */
/******/ 	(() => {
/******/ 		__webpack_require__.o = (obj, prop) => (Object.prototype.hasOwnProperty.call(obj, prop))
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/make namespace object */
/******/ 	(() => {
/******/ 		// define __esModule on exports
/******/ 		__webpack_require__.r = (exports) => {
/******/ 			if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 				Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 			}
/******/ 			Object.defineProperty(exports, '__esModule', { value: true });
/******/ 		};
/******/ 	})();
/******/ 	
/************************************************************************/
var __webpack_exports__ = {};
// This entry need to be wrapped in an IIFE because it need to be in strict mode.
(() => {
"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var tabbable__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(190);
/* harmony import */ var tabbable__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(tabbable__WEBPACK_IMPORTED_MODULE_0__);


})();

var __webpack_export_target__ = exports;
for(var i in __webpack_exports__) __webpack_export_target__[i] = __webpack_exports__[i];
if(__webpack_exports__.__esModule) Object.defineProperty(__webpack_export_target__, "__esModule", { value: true });
/******/ })()
```
### Output
#### result.code (after reformatting with prettier)
```javascript
(() => {
  var f = {
      190: (c) => {
        var b = [
            "input",
            "select",
            "textarea",
            "a[href]",
            "button",
            "[tabindex]",
            "audio[controls]",
            "video[controls]",
            '[contenteditable]:not([contenteditable="false"])',
          ],
          d = b.join(","),
          e =
            "undefined" == typeof Element
              ? function () {}
              : Element.prototype.matches ||
                Element.prototype.msMatchesSelector ||
                Element.prototype.webkitMatchesSelector;
        function a(g, j) {
          j = j || {};
          var a,
            b,
            k,
            l = [],
            m = [],
            c = g.querySelectorAll(d);
          for (
            j.includeContainer &&
              e.call(g, d) &&
              (c = Array.prototype.slice.apply(c)).unshift(g),
              a = 0;
            a < c.length;
            a++
          )
            f((b = c[a])) &&
              (0 === (k = h(b))
                ? l.push(b)
                : m.push({ documentOrder: a, tabIndex: k, node: b }));
          return m
            .sort(i)
            .map(function (a) {
              return a.node;
            })
            .concat(l);
        }
        function f(a) {
          return !(!g(a) || m(a) || 0 > h(a));
        }
        function g(a) {
          return !(a.disabled || l(a) || o(a));
        }
        function h(a) {
          var b = parseInt(a.getAttribute("tabindex"), 10);
          return isNaN(b) ? (j(a) ? 0 : a.tabIndex) : b;
        }
        function i(a, b) {
          return a.tabIndex === b.tabIndex
            ? a.documentOrder - b.documentOrder
            : a.tabIndex - b.tabIndex;
        }
        function j(a) {
          return "true" === a.contentEditable;
        }
        function k(a) {
          return "INPUT" === a.tagName;
        }
        function l(a) {
          return k(a) && "hidden" === a.type;
        }
        function m(a) {
          var b;
          return k((b = a)) && "radio" === b.type && !n(a);
        }
        function n(a) {
          if (!a.name) return !0;
          var b = (function (b) {
            for (var a = 0; a < b.length; a++) if (b[a].checked) return b[a];
          })(
            a.ownerDocument.querySelectorAll(
              'input[type="radio"][name="' + a.name + '"]'
            )
          );
          return !b || b === a;
        }
        function o(a) {
          return (
            null === a.offsetParent ||
            "hidden" === getComputedStyle(a).visibility
          );
        }
        (a.isTabbable = function (a) {
          if (!a) throw new Error("No node provided");
          return !1 !== e.call(a, d) && f(a);
        }),
          (a.isFocusable = isFocusable),
          b.concat("iframe").join(","),
          (c.exports = a);
      },
    },
    g = {};
  function a(b) {
    var d = g[b];
    if (void 0 !== d) return d.exports;
    var c = (g[b] = { exports: {} });
    return f[b](c, c.exports, a), c.exports;
  }
  (a.n = (c) => {
    var b = c && c.__esModule ? () => c.default : () => c;
    return a.d(b, { a: b }), b;
  }),
    (a.d = (d, c) => {
      for (var b in c)
        a.o(c, b) &&
          !a.o(d, b) &&
          Object.defineProperty(d, b, { enumerable: !0, get: c[b] });
    }),
    (a.o = (a, b) => Object.prototype.hasOwnProperty.call(a, b)),
    (a.r = (a) => {
      "undefined" != typeof Symbol &&
        Symbol.toStringTag &&
        Object.defineProperty(a, Symbol.toStringTag, { value: "Module" }),
        Object.defineProperty(a, "__esModule", { value: !0 });
    });
  var c,
    b = {};
  a.r(b), (c = a(190)), a.n(c);
  var d = exports;
  for (var e in b) d[e] = b[e];
  b.__esModule && Object.defineProperty(d, "__esModule", { value: !0 });
})();
```

**Comment by evantd** [comment]
Here's perhaps an easier way to repro it:
```javascript
const input =
  "/******/ (() => { // webpackBootstrap\n/******/ \tvar __webpack_modules__ = ({\n\n/***/ 190:\n/***/ ((module) => {\n\nvar candidateSelectors = [\n    'input',\n    'select',\n    'textarea',\n    'a[href]',\n    'button',\n    '[tabindex]',\n    'audio[controls]',\n    'video[controls]',\n    '[contenteditable]:not([contenteditable=\"false\"])', \n];\nvar candidateSelector = candidateSelectors.join(',');\nvar matches = typeof Element === 'undefined' ? function() {} : Element.prototype.matches || Element.prototype.msMatchesSelector || Element.prototype.webkitMatchesSelector;\nfunction tabbable(el, options) {\n    options = options || {};\n    var regularTabbables = [];\n    var orderedTabbables = [];\n    var candidates = el.querySelectorAll(candidateSelector);\n    if (options.includeContainer) {\n        if (matches.call(el, candidateSelector)) {\n            candidates = Array.prototype.slice.apply(candidates);\n            candidates.unshift(el);\n        }\n    }\n    var i, candidate, candidateTabindex;\n    for(i = 0; i < candidates.length; i++){\n        candidate = candidates[i];\n        if (!isNodeMatchingSelectorTabbable(candidate)) continue;\n        candidateTabindex = getTabindex(candidate);\n        if (candidateTabindex === 0) {\n            regularTabbables.push(candidate);\n        } else {\n            orderedTabbables.push({\n                documentOrder: i,\n                tabIndex: candidateTabindex,\n                node: candidate\n            });\n        }\n    }\n    var tabbableNodes = orderedTabbables.sort(sortOrderedTabbables).map(function(a) {\n        return a.node;\n    }).concat(regularTabbables);\n    return tabbableNodes;\n}\ntabbable.isTabbable = isTabbable;\ntabbable.isFocusable = isFocusable;\nfunction isNodeMatchingSelectorTabbable(node) {\n    if (!isNodeMatchingSelectorFocusable(node) || isNonTabbableRadio(node) || getTabindex(node) < 0) {\n        return false;\n    }\n    return true;\n}\nfunction isTabbable(node) {\n    if (!node) throw new Error('No node provided');\n    if (matches.call(node, candidateSelector) === false) return false;\n    return isNodeMatchingSelectorTabbable(node);\n}\nfunction isNodeMatchingSelectorFocusable(node) {\n    if (node.disabled || isHiddenInput(node) || isHidden(node)) {\n        return false;\n    }\n    return true;\n}\nvar focusableCandidateSelector = candidateSelectors.concat('iframe').join(',');\nfunction isFocusable(node) {\n    if (!node) throw new Error('No node provided');\n    if (matches.call(node, focusableCandidateSelector) === false) return false;\n    return isNodeMatchingSelectorFocusable(node);\n}\nfunction getTabindex(node) {\n    var tabindexAttr = parseInt(node.getAttribute('tabindex'), 10);\n    if (!isNaN(tabindexAttr)) return tabindexAttr;\n    // Browsers do not return `tabIndex` correctly for contentEditable nodes;\n    // so if they don't have a tabindex attribute specifically set, assume it's 0.\n    if (isContentEditable(node)) return 0;\n    return node.tabIndex;\n}\nfunction sortOrderedTabbables(a, b) {\n    return a.tabIndex === b.tabIndex ? a.documentOrder - b.documentOrder : a.tabIndex - b.tabIndex;\n}\nfunction isContentEditable(node) {\n    return node.contentEditable === 'true';\n}\nfunction isInput(node) {\n    return node.tagName === 'INPUT';\n}\nfunction isHiddenInput(node) {\n    return isInput(node) && node.type === 'hidden';\n}\nfunction isRadio(node) {\n    return isInput(node) && node.type === 'radio';\n}\nfunction isNonTabbableRadio(node) {\n    return isRadio(node) && !isTabbableRadio(node);\n}\nfunction getCheckedRadio(nodes) {\n    for(var i = 0; i < nodes.length; i++){\n        if (nodes[i].checked) {\n            return nodes[i];\n        }\n    }\n}\nfunction isTabbableRadio(node) {\n    if (!node.name) return true;\n    // This won't account for the edge case where you have radio groups with the same\n    // in separate forms on the same page.\n    var radioSet = node.ownerDocument.querySelectorAll('input[type=\"radio\"][name=\"' + node.name + '\"]');\n    var checked = getCheckedRadio(radioSet);\n    return !checked || checked === node;\n}\nfunction isHidden(node) {\n    // offsetParent being null will allow detecting cases where an element is invisible or inside an invisible element,\n    // as long as the element does not use position: fixed. For them, their visibility has to be checked directly as well.\n    return node.offsetParent === null || getComputedStyle(node).visibility === 'hidden';\n}\nmodule.exports = tabbable;\n\n\n/***/ })\n\n/******/ \t});\n/************************************************************************/\n/******/ \t// The module cache\n/******/ \tvar __webpack_module_cache__ = {};\n/******/ \t\n/******/ \t// The require function\n/******/ \tfunction __webpack_require__(moduleId) {\n/******/ \t\t// Check if module is in cache\n/******/ \t\tvar cachedModule = __webpack_module_cache__[moduleId];\n/******/ \t\tif (cachedModule !== undefined) {\n/******/ \t\t\treturn cachedModule.exports;\n/******/ \t\t}\n/******/ \t\t// Create a new module (and put it into the cache)\n/******/ \t\tvar module = __webpack_module_cache__[moduleId] = {\n/******/ \t\t\t// no module.id needed\n/******/ \t\t\t// no module.loaded needed\n/******/ \t\t\texports: {}\n/******/ \t\t};\n/******/ \t\n/******/ \t\t// Execute the module function\n/******/ \t\t__webpack_modules__[moduleId](module, module.exports, __webpack_require__);\n/******/ \t\n/******/ \t\t// Return the exports of the module\n/******/ \t\treturn module.exports;\n/******/ \t}\n/******/ \t\n/************************************************************************/\n/******/ \t/* webpack/runtime/compat get default export */\n/******/ \t(() => {\n/******/ \t\t// getDefaultExport function for compatibility with non-harmony modules\n/******/ \t\t__webpack_require__.n = (module) => {\n/******/ \t\t\tvar getter = module && module.__esModule ?\n/******/ \t\t\t\t() => (module['default']) :\n/******/ \t\t\t\t() => (module);\n/******/ \t\t\t__webpack_require__.d(getter, { a: getter });\n/******/ \t\t\treturn getter;\n/******/ \t\t};\n/******/ \t})();\n/******/ \t\n/******/ \t/* webpack/runtime/define property getters */\n/******/ \t(() => {\n/******/ \t\t// define getter functions for harmony exports\n/******/ \t\t__webpack_require__.d = (exports, definition) => {\n/******/ \t\t\tfor(var key in definition) {\n/******/ \t\t\t\tif(__webpack_require__.o(definition, key) && !__webpack_require__.o(exports, key)) {\n/******/ \t\t\t\t\tObject.defineProperty(exports, key, { enumerable: true, get: definition[key] });\n/******/ \t\t\t\t}\n/******/ \t\t\t}\n/******/ \t\t};\n/******/ \t})();\n/******/ \t\n/******/ \t/* webpack/runtime/hasOwnProperty shorthand */\n/******/ \t(() => {\n/******/ \t\t__webpack_require__.o = (obj, prop) => (Object.prototype.hasOwnProperty.call(obj, prop))\n/******/ \t})();\n/******/ \t\n/******/ \t/* webpack/runtime/make namespace object */\n/******/ \t(() => {\n/******/ \t\t// define __esModule on exports\n/******/ \t\t__webpack_require__.r = (exports) => {\n/******/ \t\t\tif(typeof Symbol !== 'undefined' && Symbol.toStringTag) {\n/******/ \t\t\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });\n/******/ \t\t\t}\n/******/ \t\t\tObject.defineProperty(exports, '__esModule', { value: true });\n/******/ \t\t};\n/******/ \t})();\n/******/ \t\n/************************************************************************/\nvar __webpack_exports__ = {};\n// This entry need to be wrapped in an IIFE because it need to be in strict mode.\n(() => {\n\"use strict\";\n__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var tabbable__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(190);\n/* harmony import */ var tabbable__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(tabbable__WEBPACK_IMPORTED_MODULE_0__);\n\n\n})();\n\nvar __webpack_export_target__ = exports;\nfor(var i in __webpack_exports__) __webpack_export_target__[i] = __webpack_exports__[i];\nif(__webpack_exports__.__esModule) Object.defineProperty(__webpack_export_target__, \"__esModule\", { value: true });\n/******/ })()\n;";
console.log(
  require("@swc/core").minifySync(input, {
    compress: {},
    module: false,
    ecma: 2015,
    mangle: true,
    sourceMap: undefined,
  }).code
);
```

**Comment by evantd** [comment]
This was still broken in 1.2.146 and was fixed in 1.2.147. I'm leaving this open in case you want to add a test case based on it, but the underlying problem seems to be solved.

**Comment by kdy1** [comment]
Can you still reproduce?
I think it's fixed

**Comment by kdy1** [comment]
Oh sorry, I'll close this
