### ISSUE TITLE
[CORE] 0.20.5 Compilation fails

### ISSUE THREAD

**Issue by kwonoj** [swc-project/swc#5744]
### Describe the bug

```
no method named `maybe_par` found for mutable reference `&mut Remover` in the current scope
    --> /Users/ojkwon/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_transforms_optimization-0.160.5/src/simplify/branch/mod.rs:1248:14
     |
1248 |         self.maybe_par(cpu_count() * 8, n, |v, n| {
```

### Expected behavior

- 

### Version

0.20.5

**Comment by kwonoj** [comment]
@kdy1 fyi, since we're trying to move forward to stable / semver complaiant swc_core model I'm trying to file issues with latest published versions.

Ideally, we should find a way to avoid these things before publish. Will file separate issue.

**Comment by kwonoj** [comment]
https://github.com/swc-project/swc/issues/5745

**Comment by kwonoj** [comment]
@kdy1 this still occurs, but I'm not sure where it exactly comes from. `maybe_par` looks like coming from ecma_utils, but it is already bumped up to the latest version.

**Comment by kdy1** [comment]
Is it `0.101.1`? https://github.com/swc-project/swc/commit/c44fd43b153992e5fd0700c09fa5b4b84a1108c7

**Comment by kdy1** [comment]
This is fixed by https://github.com/swc-project/swc/commit/95119be5b2deba94dbc96afebe6ceb22d8ad5062

We now use `-D` flag so updating `swc_core` will be always enough

**Comment by kdy1** [comment]
For example see https://github.com/swc-project/swc/commit/8493c88b06c51b7857d05c6efcc17e716353ac5c

**Comment by kwonoj** [comment]
It isn't, I picked up latest `swc_core` and it still fails. `ecma_utils` poining 0.101.2

<img width="352" alt="image" src="https://user-images.githubusercontent.com/1210596/188533262-084aa0be-510d-4297-9996-9c3f150ee88d.png">

**Comment by kwonoj** [comment]
```

error[E0599]: no method named `maybe_par` found for mutable reference `&mut Remover` in the current scope
    --> /Users/ojkwon/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_transforms_optimization-0.160.8/src/simplify/branch/mod.rs:1272:14
     |
1272 |         self.maybe_par(cpu_count() * 8, &mut *stmts, |visitor, stmt| {
     |              ^^^^^^^^^ method not found in `&mut Remover
```

transforms_optimization 0.160.8 fails with it

**Comment by kdy1** [comment]
It's published before https://github.com/swc-project/swc/commit/95119be5b2deba94dbc96afebe6ceb22d8ad5062

**Comment by kdy1** [comment]
See commit history. This is fixed by the commit I mentioned, and the commit is quite new one

**Comment by kwonoj** [comment]
I don't know how commit https://github.com/swc-project/swc/commit/95119be5b2deba94dbc96afebe6ceb22d8ad5062 is related with this.

Current compilation failure comes from `swc_core`, not `@swc/core`. `swc_core` 0.20.8 imports transforms_optimization 0.160.8 which hits this build failure.

**Comment by kdy1** [comment]
You can run `cargo update`
I published a new version, and it means the latest version of `swc_core` compiles

**Comment by kdy1** [comment]
@kwonoj See https://github.com/swc-project/swc/commit/95119be5b2deba94dbc96afebe6ceb22d8ad5062#diff-90ebe49161fbb2e2a5228308646f604e16cac15b007be89c0a35b41f7ece387aL41 
this line

**Comment by kwonoj** [comment]
@kdy1 I think I'm confused. Which package / version should be updated? 

crates.io shows

- swc_core 0.20.8 

<img width="300" alt="image" src="https://user-images.githubusercontent.com/1210596/188534222-121c1c0f-e571-4cc4-a9e1-dbb45a34d196.png">

- swc_ecma_transforms_optimization 0.160.8
<img width="330" alt="image" src="https://user-images.githubusercontent.com/1210596/188534246-bc0486e4-7b05-4ea5-9904-c6c71af07e76.png">

- swc_ecma_utils 0.101.2
<img width="310" alt="image" src="https://user-images.githubusercontent.com/1210596/188534315-4b0ed810-fb57-4192-beb5-6c9ca7d52682.png">

And current codebases are using all of them as latest, nothing to update.

**Comment by kdy1** [comment]
Hmm.. I don't have any idea if all crates are up-to-date

**Comment by kdy1** [comment]
https://github.com/swc-project/plugins/pull/82
Seems like it's working.

**Comment by kwonoj** [comment]
It's bit stale and swc_core have multiple releases after this, so let me close & reopen if necessary.
