### ISSUE TITLE
Imports use absolute paths on windows instead of relative

### ISSUE THREAD

**Issue by martijnimhoff** [swc-project/swc#7806]
### Describe the bug

I'm using @swc/core on version 1.3.76. On version 1.3.74, i do not have this problem. I'm also on windows. 

When I compile my TS into JS, my imports break because in the output an absolute path is used. This path leads to the uncompiled TS files. Please have a look at the expected vs actual behavior. 

### Config

```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "sourceMaps": true,
  "module": {
    "type": "commonjs"
  },
  "jsc": {
    "target": "es2022",
    "parser": {
      "syntax": "typescript"
    },
    "keepClassNames": true,
    "baseUrl": "./"
  },
  "minify": false
}
```

### Expected behavior

I'm expecting this output:

```
const _admin = /*#__PURE__*/ _interop_require_default(require("./routes/admin"));
```

### Actual behavior

I'm getting this output:

```
const _admin = /*#__PURE__*/ _interop_require_default(require("C:/Projects/example-project/src/routes/admin"));
```

### Version

1.3.76

### Additional context

On 1.3.74 I'm getting the expected behavior.

**Comment by wp-harm** [comment]
This is a continuation from this issue: https://github.com/swc-project/swc/issues/7603#issuecomment-1680151040

A reproduction was asked for. Using this method the issue can be reproduced:
1. Clone: https://github.com/kenso312/nestjs-v10-webpack-boilerplate (it's not mine, but it has SWC + path alias enabled)
2. Install deps by running `pnpm install` (install `pnpm` using this command if you don't have it: `npm install -g pnpm`)
3. Copy env file: `cp .env.example .env`
4. Run `pnpm dev`
5. On Windows this will fail and on MacOS it works (I don't know about Linux but I'm assuming it will work)

I think the issue should be re-opened as it seems the issue has become much more clear 🙂

**Comment by kdy1** [comment]
Hmm.. It seems like a too large app to debug. https://antfu.me/posts/why-reproductions-are-required

**Comment by kdy1** [comment]
I accept next.js app as repro because I'm familiar with it, but digging into a framework is extremely time consuming

**Comment by wp-harm** [comment]
I see, I understand your time a valuable in that sense. I'll see if I can make simpler repo myself 👍

**Comment by kdy1** [comment]
@wp-harm  Can you create a smaller repro using nest.js starter kit? I found that https://github.com/KirianCaumes/nestjs-bug-swc-import is small enough

**Comment by kdy1** [comment]
And it looks like a starter kit

**Comment by wp-harm** [comment]
I think I did you one better. This repo is the root of the issue. Essentially I did a deep dive into the NestJS CLI repo and line calling the SWC compiler is the following: https://github.com/nestjs/nest-cli/blob/master/lib/compiler/swc/swc-compiler.ts#L165

The input to that call I distilled into this repo: https://github.com/harm-less/swc-path-bug. 
This input can be seen in `script/compile.js`. The only thing I changed is the `process.cwd()` to make sure the input would work on your PC as well.

I tested this repo on both my Windows and MacOS system and only the latter worked. The resulting compiled JS is exactly as @martijnimhoff mentioned in his initial message on both operating systems. 

I did discover a few workarounds during my research, perhaps you can make more sense of them than I can:
1. If you disable/remove `swcOptions.jsc.baseUrl` from the compile script, on Windows it suddenly starts working.
2. What also seems to work is changing `swcOptions.jsc.paths` to `['@utils/*': [ 'dist/utils/*' ]]` because then the absolute path is pointing to the correct dir (for NestJS this is actually a workaround for the time being. So to anyone encountering this problem, manually add the same paths to your `.swcrc` and point to your dist folder for each of the paths)

I do believe those workaround are not the way to go, so hopefully using are there findings you can more easily discover the root problem @kdy1 💪

**Comment by wp-harm** [comment]
https://github.com/nestjs/nest/issues/11937

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/commit/5c4bfa61f9e4f7732bc1a9da6cd25f52e593a374 looks like the cause

**Comment by kdy1** [comment]
So my guess is a difference between UNC and normal path.

**Comment by greut** [comment]
> @wp-harm Can you create a smaller repro using nest.js starter kit? I found that https://github.com/KirianCaumes/nestjs-bug-swc-import is small enough

Taking that repo, bumping everything to latest (see below for the versions), it's still producing a similar error.

```
$ npm run start

> test-nestjs@0.0.1 start
> nest start

✔  TSC  Initializing type checker...
>  TSC  Found 0 issues.
>  SWC  Running...
thread 'thread 'thread 'thread '<unnamed><unnamed><unnamed><unnamed>' panicked at '' panicked at '' panicked at '' panicked at 'base_dir(`src`) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly. This cannot be deduced by SWC itself because SWC is a transpiler and it does not try to resolve project details. In other works, SWC does not know which directory should be used as a base directory. It can be deduced if `.swcrc` is used, but if not, there are many candidates. e.g. the directory containing `package.json`, or the current working directory. Because of that, the caller (typically the developer of the JavaScript package) should specify it. If you see this error, please report an issue to the package author.base_dir(`src`) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly. This cannot be deduced by SWC itself because SWC is a transpiler and it does not try to resolve project details. In other works, SWC does not know which directory should be used as a base directory. It can be deduced if `.swcrc` is used, but if not, there are many candidates. e.g. the directory containing `package.json`, or the current working directory. Because of that, the caller (typically the developer of the JavaScript package) should specify it. If you see this error, please report an issue to the package author.base_dir(`src`) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly. This cannot be deduced by SWC itself because SWC is a transpiler and it does not try to resolve project details. In other works, SWC does not know which directory should be used as a base directory. It can be deduced if `.swcrc` is used, but if not, there are many candidates. e.g. the directory containing `package.json`, or the current working directory. Because of that, the caller (typically the developer of the JavaScript package) should specify it. If you see this error, please report an issue to the package author.base_dir(`src`) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly. This cannot be deduced by SWC itself because SWC is a transpiler and it does not try to resolve project details. In other works, SWC does not know which directory should be used as a base directory. It can be deduced if `.swcrc` is used, but if not, there are many candidates. e.g. the directory containing `package.json`, or the current working directory. Because of that, the caller (typically the developer of the JavaScript package) should specify it. If you see this error, please report an issue to the package author.', ', ', ', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_transforms_module-0.173.38/src/path.rs/usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_transforms_module-0.173.38/src/path.rs/usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_transforms_module-0.173.38/src/path.rs/usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_transforms_module-0.173.38/src/path.rs::::104104104104::13::13
1313
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


thread '<unnamed>' panicked at 'base_dir(`src`) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly. This cannot be deduced by SWC itself because SWC is a transpiler and it does not try to resolve project details. In other works, SWC does not know which directory should be used as a base directory. It can be deduced if `.swcrc` is used, but if not, there are many candidates. e.g. the directory containing `package.json`, or the current working directory. Because of that, the caller (typically the developer of the JavaScript package) should specify it. If you see this error, please report an issue to the package author.', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_transforms_module-0.173.38/src/path.rs:104:13
failed to handle: base_dir(`src`) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly. This cannot be deduced by SWC itself because SWC is a transpiler and it does not try to resolve project details. In other works, SWC does not know which directory should be used as a base directory. It can be deduced if `.swcrc` is used, but if not, there are many candidates. e.g. the directory containing `package.json`, or the current working directory. Because of that, the caller (typically the developer of the JavaScript package) should specify it. If you see this error, please report an issue to the package author.
failed to handle: base_dir(`src`) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly. This cannot be deduced by SWC itself because SWC is a transpiler and it does not try to resolve project details. In other works, SWC does not know which directory should be used as a base directory. It can be deduced if `.swcrc` is used, but if not, there are many candidates. e.g. the directory containing `package.json`, or the current working directory. Because of that, the caller (typically the developer of the JavaScript package) should specify it. If you see this error, please report an issue to the package author.
failed to handle: base_dir(`src`) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly. This cannot be deduced by SWC itself because SWC is a transpiler and it does not try to resolve project details. In other works, SWC does not know which directory should be used as a base directory. It can be deduced if `.swcrc` is used, but if not, there are many candidates. e.g. the directory containing `package.json`, or the current working directory. Because of that, the caller (typically the developer of the JavaScript package) should specify it. If you see this error, please report an issue to the package author.
failed to handle: base_dir(`src`) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly. This cannot be deduced by SWC itself because SWC is a transpiler and it does not try to resolve project details. In other works, SWC does not know which directory should be used as a base directory. It can be deduced if `.swcrc` is used, but if not, there are many candidates. e.g. the directory containing `package.json`, or the current working directory. Because of that, the caller (typically the developer of the JavaScript package) should specify it. If you see this error, please report an issue to the package author.
failed to handle: base_dir(`src`) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly. This cannot be deduced by SWC itself because SWC is a transpiler and it does not try to resolve project details. In other works, SWC does not know which directory should be used as a base directory. It can be deduced if `.swcrc` is used, but if not, there are many candidates. e.g. the directory containing `package.json`, or the current working directory. Because of that, the caller (typically the developer of the JavaScript package) should specify it. If you see this error, please report an issue to the package author.
Failed to compile 5 files with swc.
```

And trying to set an absolute path there only remove the first `/` to then complain with the same issue.

```
$ npm list
test-nestjs@0.0.1 .../nestjs-bug-swc-import
├── @nestjs/cli@10.1.14
├── @nestjs/common@10.2.1
├── @nestjs/core@10.2.1
├── @nestjs/platform-express@10.2.1
├── @nestjs/schematics@10.0.2
├── @nestjs/testing@10.2.1
├── @swc/cli@0.1.62
├── @swc/core@1.3.78
├── @types/express@4.17.17
├── @types/jest@29.5.3
├── @types/node@20.5.0
├── @types/supertest@2.0.12
├── @typescript-eslint/eslint-plugin@6.4.1
├── @typescript-eslint/parser@6.4.1
├── eslint-config-prettier@9.0.0
├── eslint-plugin-prettier@5.0.0
├── eslint@8.47.0
├── jest@29.6.2
├── prettier@3.0.2
├── reflect-metadata@0.1.13
├── rxjs@7.8.1
├── source-map-support@0.5.21
├── supertest@6.3.3
├── ts-jest@29.1.1
├── ts-loader@9.4.4
├── ts-node@10.9.1
├── tsconfig-paths@4.2.0
└── typescript@5.1.6
```

Thanks for your time and consideration!

**Comment by kdy1** [comment]
@greut Can you share the repro, not only versions?

**Comment by greut** [comment]
> @greut Can you share the repro, not only versions?

it's that one + `npm update` https://github.com/KirianCaumes/nestjs-bug-swc-import

**Comment by greut** [comment]
the latest release (10.1.15) fixed it: https://github.com/nestjs/nest-cli/commit/deddb98e :heart:

**Comment by kdy1** [comment]
Can you try `v1.3.79` once https://github.com/swc-project/swc/actions/runs/5972622833 is finished?

**Comment by kdy1** [comment]
@wp-harm Can you try v1.3.80?

**Comment by kdy1** [comment]
I'm pretty sure this is fixed

**Comment by wp-harm** [comment]
@kdy1 Will do! Tomorrow I'll be back at my Windows system and try it out 👍

**Comment by powerfulyang** [comment]
@kdy1 v1.3.80 didn't fix. 
Here is the reproduce https://github.com/powerfulyang/swc-path-bug/actions/runs/5998429217/job/16266697311#step:7:11

**Comment by kdy1** [comment]
Okay, it's not reproducible usnig the Rust testing system of SWC. So my guess is related to `jsc.baseUrl: process.cwd()`.
I'll test it using JS testing system

**Comment by kdy1** [comment]
The repro works if I give "\\?\C:\Users\MSI\projects\swc-win\swc-path-bug" as `jsc.baseUrl`.

**Comment by powerfulyang** [comment]
> The repro works if I give `\\?\C:\Users\MSI\projects\swc-win\swc-path-bug` as `jsc.baseUrl`.

YES, `\\?\C:\Users\MSI\projects\swc-win\swc-path-bug` works.

**Comment by powerfulyang** [comment]
https://github.com/powerfulyang/swc-path-bug/actions/runs/6021221240/job/16333735691#step:7:11

**Comment by powerfulyang** [comment]
So, should the user manually set the prefix?

**Comment by kdy1** [comment]
No, I'll normalize it from the Rust code. It's not matter of prefix, but it's UNC path of Windows

**Comment by viniciussantos45** [comment]
## Using NestJS

After updating `@swc/core` to version `1.3.81` it started working for `@nestjs/cli` version `10.1.16`
## My current setup:
### tsconfig.json
```json
{
  "compilerOptions": {
   ...
    "outDir": "./dist",
    "baseUrl": ".",
    "paths": {
      "@common/*": ["src/common/*"],
      "@config/*": ["src/config/*"],
      "@modules/*": ["src/modules/*"]
    }
   ...
  }
}

```

### .swcrc
```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "sourceMaps": true,
  
  "minify": false,
  "jsc": {
    ...
    "baseUrl": "./",
    "paths": {
      "@common/*": ["src/common/*"],
      "@config/*": ["src/config/*"],
      "@modules/*": ["src/modules/*"]
    },
    ...
  }
}
```

### nest-cli-.json
```json
{
  "$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "deleteOutDir": true,
    "builder": "swc",
    "typeCheck": true
  }
}
```

**Comment by BlindKai** [comment]
That is actually pretty weird.
I've just tried to create a plain project using the following configs:

```json
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
  ...
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@swc/cli": "^0.1.62",
    "@swc/core": "^1.3.83",
```

And the only time when the project starts is when the paths are specified in both `.swcrc` and `tsconfig.json`

```json
    "paths": {
      "@common/*": ["src/common/*"],
      "@config/*": ["src/config/*"],
      "@modules/*": ["src/modules/*"]
    },
```

![image](https://github.com/swc-project/swc/assets/43204960/d7bc3203-4e49-4e06-b6f2-0e2eb0436c02)

Without specifying these, I'm getting errors:

![image](https://github.com/swc-project/swc/assets/43204960/77e52de4-f0d5-4f89-aeb8-f911c9e4e189)

**Comment by Makoehle** [comment]
In my case VS-Code was automatically importing paths like so `src/moduleOne/moduleOne.service.ts` which lead to this error. I was able to fix the error my adapting one of your comments and add the following to my `tsconfig.json`.

```json
    "paths": {
      "src/*": ["src/*"]
    }
```
