### ISSUE TITLE
Jest + SWC resolves index.js instead of index.ts

### ISSUE THREAD

**Issue by iicdii** [swc-project/swc#7907]
### Describe the bug

```
 FAIL  src/__tests__/App.test.tsx
  ● Test suite failed to run

Cannot find module './src/logger/index.js' from '../../packages/utils/index.ts'
```
Before upgrading the SWC package version, the test suite was passing as expected. However, after upgrading the version and adding settings for an absolute path (`baseUrl: '.'`) in jest config, the same test now fails with an error.

```
packages
  utils
    src
      logger
        index.ts (-> It's `.ts`, not `.js`)
    date.ts
    index.ts
```

### Input code

```typescript
// apps/app/App.tsx
import { dateToTimestamp } from 'utils';
```

// packages/utils/package.json
```json
{
  "name": "utils",
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "main": "./index.ts",
  "devDependencies": {
    "tsconfigs": "workspace:*"
  }
}
```

```ts
// packages/utils/index.ts
export * from './src/date';
export * from './src/logger';
```

```ts
// packages/utils/logger/index.ts
export { default as createLogSender } from './createLogSender';
export { default as createLogManager } from './createLogManager';

export type * from './types';
```

```json
// apps/app/tsconfig.json
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"],
      "@core/*": ["../../packages/core/src/*"]
    },

    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,

    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",

    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "references": [{ "path": "./tsconfig.node.json" }],
  "include": ["src", ".storybook/*"],
  "exclude": ["cypress.config.ts", "node_modules"]
}
```

### Config

```js
// apps/app/jest.config.cjs

const createJestConfig = require('jest-config');

module.exports = createJestConfig({
  baseUrl: '.',
  paths: {
    '@/*': ['src/*'],
  },
});
```

```js
// packages/jest-config/index.js
module.exports = function ({ setupFilesAfterEnv = [], testMatch, baseUrl, paths = {} }) {
  return {
    testEnvironment: 'jsdom',
    setupFilesAfterEnv: ['jest-config/setupTests.js', ...setupFilesAfterEnv],
    testMatch: testMatch ?? ['<rootDir>/src/__tests__/**/*.test.(ts|tsx)'],
    transform: {
      '^.+\\.(js|jsx|ts|tsx)$': [
        '@swc/jest',
        {
          sourceMaps: true,
          jsc: {
            parser: {
              syntax: 'typescript',
              tsx: true,
            },
            transform: {
              react: {
                runtime: 'automatic',
              },
            },
            baseUrl,
            paths,
          },
        },
      ],
    },
    moduleNameMapper: {
      '\\.(css|less|scss|sass)$': 'identity-obj-proxy',
      '\\.(jpg|jpeg|png|gif|svg|eot|otf|webp|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
        'jest-transform-stub',
    },
  };
};
```

### SWC Info output

    Operating System:
        Platform: darwin
        Arch: arm64
        Machine Type: arm64
        Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
        CPU: (10 cores)
            Models: Apple M1 Max

    Binaries:
        Node: 20.4.0
        npm: 9.7.2
        Yarn: 1.22.19
        pnpm: 8.7.1

    Relevant Packages:
        @swc/core: 1.3.82
        @swc/helpers: N/A
        @swc/types: N/A
        typescript: 5.0.4

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

### Expected behavior

The module import should automatically search for index.ts instead of index.js when the file extension is omitted.

### Version

1.3.82

### Additional context

Working
- "[@swc/core](https://npmjs.com/package/@swc/core)": "[1.3.71](https://npmjs.com/package/@swc/core)",
- "[@swc/jest](https://npmjs.com/package/@swc/jest)": "[0.2.27](https://npmjs.com/package/@swc/jest)",
- "[jest](https://npmjs.com/package/jest)": "[29.5.0](https://npmjs.com/package/jest)",

Not Working
- "[@swc/core](https://npmjs.com/package/@swc/core)": "[1.3.82](https://npmjs.com/package/@swc/core)",
- "[@swc/jest](https://npmjs.com/package/@swc/jest)": "[0.2.29](https://npmjs.com/package/@swc/jest)",
- "[jest](https://npmjs.com/package/jest)": "[29.6.4](https://npmjs.com/package/jest)",

**Comment by kdy1** [comment]
Already fixed by https://github.com/swc-project/swc/pull/7906

**Comment by vizio360** [comment]
I'm still having this issue.
I'm using:
`@swc/core 1.3.82`
`@swc/jest 0.2.29`

this is my swcrc config:
```
{
    "$schema": "https://json.schemastore.org/swcrc",
    "sourceMaps": true,
    "jsc": {
        "parser": {
            "syntax": "typescript",
            "decorators": true,
            "dynamicImport": true
        },
        "transform": {
            "legacyDecorator": true,
            "decoratorMetadata": true
        },
        "baseUrl": ".",
        "target": "es2017"
    },
    "minify": false,
    "module": {
        "type": "commonjs"
    }
}
```

and my jest config
```
"jest": {
        "testTimeout": 30000,
        "moduleFileExtensions": [
            "js",
            "json",
            "ts"
        ],
        "rootDir": ".",
        "testRegex": ".*\\.(spec|e2e-spec)\\.ts$",
        "transform": {
            "^.+\\.ts$": "@swc/jest"
        },
        "collectCoverageFrom": [
            "src/**/*.ts"
        ],
        "coveragePathIgnorePatterns": [
            "main.ts$",
            "constants.ts$",
            ".spec.ts$",
            "index.ts$",
            "scripts"
        ],
        "coverageDirectory": "./coverage",
        "coverageProvider": "v8",
        "testEnvironment": "node",
        "testResultsProcessor": "jest-sonar-reporter",
        "setupFiles": [
            "<rootDir>/test/setEnvVars.js"
        ]
    },
```

and the error is 
`Cannot find module '../common/enums/index.js' from 'src/config/testImport.spec.ts'`

**Comment by kdy1** [comment]
It's not published yet

**Comment by vizio360** [comment]
> It's not published yet

Sorry I misread the release page on github
