### ISSUE TITLE
Unable to minify css using `@swc/css` when there's a calc

### ISSUE THREAD

**Issue by tanhauhau** [swc-project/swc#7939]
### Describe the bug

When using `@swc/css` to minify a css file that contains `calc()` it will throw the following error:

```
thread '<unnamed>' panicked at 'cannot access a scoped thread local variable without calling `set` first', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.1/src/lib.rs:168:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: failed to handle: cannot access a scoped thread local variable without calling `set` first] {
  code: 'GenericFailure'
}
```

### Input code

```typescript
const { minify } = require('@swc/css');
(async function () {
  const result = await minify(Buffer.from(`
    .class {
      width: calc(1% + 1px);
    }
  `));
  console.log({ result });
})();
```

### Expected behavior

should not throw any error

### Version

@swc/css@0.0.28

**Comment by neoGeneva** [comment]
This bug also impacts other CSS functions too, such as `alpha()`, e.g.

```javascript
const { minify } = require("@swc/css");
(async function () {
  const result = await minify(
    Buffer.from(`
    .class {
      filter: alpha(opacity=60);
    }
  `)
  );
  console.log({ result });
})();
```

**Comment by kdy1** [comment]
Fixed by https://github.com/swc-project/extra-bindings/pull/44

**Comment by neoGeneva** [comment]
Hey @kdy1, this problem isn't entirely resolved. `calc` and `alpha` still can't be translated, the error has just changed from ``failed to handle: cannot access a scoped thread local variable without calling `set` first`` to `Expected Declaration value`

So you want to re-open this issue, or should we create a new one?

**Comment by kdy1** [comment]
Pelase open a new issue. It's about parsing, not minification
