### ISSUE TITLE
cargo: failed to select a version for the requirement `swc_ecma_transforms = "^0.226.37"`

### ISSUE THREAD

**Issue by mischnic** [swc-project/swc#8270]
### Describe the bug

I tried to bump the swc crate version in Parcel:

```
error: failed to select a version for the requirement `swc_ecma_transforms = "^0.226.37"`
candidate versions found which didn't match: 0.226.36, 0.226.35, 0.226.34, ...
location searched: crates.io index
required by package `swc_ecma_preset_env v0.203.38`
    ... which satisfies dependency `swc_ecma_preset_env = "^0.203.38"` of package `swc_core v0.86.52`
    ... which satisfies dependency `swc_core = "^0.86.52"` of package `parcel-js-swc-core v0.1.0
perhaps a crate was updated and forgotten to be re-vendored?
```

### Input code

```typescript
...
```

### Config

```json
...
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/

### SWC Info output

```toml
swc_core = { version = "0.86.52", features = [
  "common",
  "common_ahash",
  "common_sourcemap",
  "ecma_ast",
  "ecma_codegen",
  "ecma_parser",
  "ecma_preset_env",
  "ecma_transforms",
  "ecma_transforms_compat",
  "ecma_transforms_optimization",
  "ecma_transforms_proposal",
  "ecma_transforms_react",
  "ecma_transforms_typescript",
  "ecma_visit",
] }
```

### Expected behavior

...

### Actual behavior

...	

### Version

...

**Comment by kdy1** [comment]
Should be fixed now.

https://github.com/swc-project/bot/actions/runs/6825217583/job/18562616275 is the cause

**Comment by mischnic** [comment]
I'm still having problems, even when completely removing my old lockfile:


```
error: failed to select a version for the requirement `swc_ecma_codegen = "^0.146.24"`
candidate versions found which didn't match: 0.146.23, 0.146.22, 0.146.21, ...
location searched: crates.io index
required by package `swc_core v0.86.53`
    ... which satisfies dependency `swc_core = "^0.86.53"` of package `parcel-js-swc-core v0.1.0`
perhaps a crate was updated and forgotten to be re-vendored?
```

with
```toml
swc_core = { version = "0.86.53", features = [
  "common",
  "common_ahash",
  "common_sourcemap",
  "ecma_ast",
  "ecma_codegen",
  "ecma_parser",
  "ecma_preset_env",
  "ecma_transforms",
  "ecma_transforms_compat",
  "ecma_transforms_optimization",
  "ecma_transforms_proposal",
  "ecma_transforms_react",
  "ecma_transforms_typescript",
  "ecma_visit",
] }
```

**Comment by kdy1** [comment]
It should be really fixed now
